### ISSUE TITLE
qs, hogan.js, algoliasearch-helper. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by thiboot** [algolia/angular-instantsearch#894] opened 2022-01-28 00:26 UTC
Need to update or find alternatives for these 3 CommonJS or AMD dependencies.

`Warning: project/node_modules/instantsearch.js/es/lib/routers/history.js depends on 'qs'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: project/node_modules/instantsearch.js/es/lib/utils/renderTemplate.js depends on 'hogan.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: project/node_modules/instantsearch.js/es/widgets/index/index.js depends on 'algoliasearch-helper'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

**Comment by Haroenv** [comment] 2022-01-28 09:31
Hi @thiboot, thanks for your issue. We have these updates planned for the future, but it requires a significant amount of work. For the mean time, there actually aren't any parts of those libraries that exist, but aren't used. That means that while there are slight possible tree shakings happening, nothing significant would change. 

this is a duplicate of #810 

As such, and since this is only a warning, not an error, I will close this issue. Thanks!

**Closed by Haroenv** 2022-01-28 09:31 UTC
