### ISSUE TITLE
Compilation error: Cannot find module 'places.js' or its corresponding type declarations.

### ISSUE THREAD

**Issue by mazenaboelanin** [algolia/angular-instantsearch#989] opened 2023-03-15 14:22 UTC
**Describe the bug 🐛**

- Receiving a compilation error `cannot find module 'places.js'` when trying to use angular-instantsearch `version 4.3.0` or the latest `version  4.4.0`.
- Tried to add places using `yarn add @types/places` and it gives the same error

**Expected behavior 💭**

Successful compilation.

**Screenshots 🖥**
![cant-find-places js](https://user-images.githubusercontent.com/39408280/225336191-c59d977b-64cc-4e79-bfb0-54d3f0e4a7e3.jpeg)

**Environment:**

 - OS: mac
 - Browser: all
 - Versions:
    "angular-instantsearch": "^4.4.0",
    "@angular/core": "^14.2.0",
    `node: 16.17.0` and ` node: 18.10.0`
`    yarn: 1.22.19`

**Comment by Haroenv** [comment] 2023-03-15 14:33
duplicate of #988

**Closed by Haroenv** 2023-03-15 14:33 UTC
