### ISSUE TITLE
Angular InstantSearch error: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by sajidniazi** [algolia/angular-instantsearch#296] opened 2018-10-14 15:59 UTC
Hello,

I have integrated Angular InstantSearch, and facets are working fine. But if I type anything in the search box, it doesn't work and I see the below error in Chrome Console:

NgAisCurrentRefinements.html:6 ERROR TypeError: Cannot read property 'charAt' of undefined
    at capitalize (angular-instantsearch.js:70)
    at angular-instantsearch.js:537
    at Array.reduce (<anonymous>)
    at NgAisCurrentRefinements.get [as refinements] (angular-instantsearch.js:526)
    at Object.eval [as updateDirectives] (NgAisCurrentRefinements.html:15)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11054)
    at checkAndUpdateView (core.js:10451)
    at callViewAction (core.js:10692)
    at execEmbeddedViewsAction (core.js:10655)
    at checkAndUpdateView (core.js:10452)

---
    "@types/algoliasearch": "^3.27.8",
    "algoliasearch": "^3.30.0",
    "angular-instantsearch": "^2.0.4",

**Comment by Haroenv** [comment] 2018-10-15 07:47
Can you make the code you are using with this available? 

We have a template http://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch

Note for other maintainers, this is probably because of the query, but I'm not sure yet without reproduction

**Comment by sajidniazi** [comment] 2018-10-15 13:10
Please close this issue. It was probably due to a misconfigured Algolia index / invalid data in it. I cleared the index and re-inserted data into it, and now the facets and full text works fine in a test app using Angular InstantSearch. Thanks for your help!

**Comment by Haroenv** [comment] 2018-10-15 15:15
Thanks @sajidniazi, I wonder which kind of situation caused this though? Can you remember anything more?

**Comment by sajidniazi** [comment] 2018-10-15 22:29
Hello, the issue actually still exists, so I have re-opened it.

https://codesandbox.io/s/0p4r9j77pp

When we add the below line to the code, and type something to search "Restore old photos":
<ais-current-refinements [clearsQuery]="true"></ais-current-refinements> 

We start seeing the errors related with the "capitalize" function in the Console and the whole browser window containing codesandbox.io link freezes.

<img width="1674" alt="screen shot 2018-10-15 at 23 24 36" src="https://user-images.githubusercontent.com/4688859/46981851-f90e3400-d0d1-11e8-82f0-5b1011810c58.png">

**Comment by tkrugg** [comment] 2018-10-30 15:44
Hi @sajidniazi. I'm happy to annouce this issue has been fixed now inside [instantsearch.js@2.10.4](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#2104-2018-10-30).
I've made the update to your [codesandbox sample](https://codesandbox.io/s/mo6wrvn8q8) to check that it works.

**Comment by tkrugg** [comment] 2018-10-31 12:20
I'm closing this for now @sajidniazi. Let us know if you run into more issues.

**Closed by tkrugg** 2018-10-31 12:20 UTC
